FC=gfortran
FFLAGS= -O3 -fPIC -std=f2003 -ffree-form -fopt-info -fmax-errors=1 -fbounds-check -Werror
SRC=utils.f90	algebra.f90	 elasticity.f90 slipGeom.f90 slipKinetics.f90 slipHardening.f90 thermoExpansion.f90 \
		crysPlasMat.f90 crysPlasMatPoint.f90
OBJECTS := $(patsubst %.f90, %.o, $(SRC))
capsul: $(OBJECTS)
	$(FC) $(SRC) -fPIC -shared -o libcapsul.so
utils.o: utils.f90
	$(FC) $(FFLAGS) -c $< -o $@
algebra.o: algebra.f90 utils.o
	$(FC) $(FFLAGS) -c $< -o $@
elasticity.o:	elasticity.f90 utils.o
	$(FC) $(FFLAGS) -c $< -o $@
slipGeom.o:	slipGeom.f90 utils.o algebra.o
	$(FC) $(FFLAGS) -c $< -o $@
slipKinetics.o:	slipKinetics.f90 utils.o algebra.o
	$(FC) $(FFLAGS) -c $< -o $@
slipHardening.o:	slipHardening.f90 utils.o algebra.o
	$(FC) $(FFLAGS) -c $< -o $@
thermoExpansion.o:	thermoExpansion.f90 utils.o algebra.o
	$(FC) $(FFLAGS) -c $< -o $@
crysPlasMat.o:	crysPlasMat.f90 elasticity.o slipGeom.o slipKinetics.o	\
		                slipHardening.o thermoExpansion.o utils.o algebra.o
	$(FC) $(FFLAGS) -c $< -o $@
crysPlasMatPoint.o:	crysPlasMatPoint.f90 crysPlasMat.o
	$(FC) $(FFLAGS) -c $< -o $@
clean:
	rm *.mod *.o
.PHONY: clean


