
  use typeCrysElas
  use typeCrysElasIso
  use typeCrysElasCubic
  use typeCrysElasAniso

  use typeThermoExpa
  use typeThermoExpaIso
  use typeThermoExpaAniso

  use typeSlipGeom
  use typeSlipGeomFCC
  use typeSlipGeomBCC
  use typeSlipGeomHCP
  use typeSlipGeomUser

  use typeSlipKine
  use typeSlipKinePowLaw1

  use typeSlipHard
  use typeSlipHardAN
  use typeSlipHardVT
  use typeSlipHardVK

